<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCZrcamn\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCZrcamn/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCZrcamn.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCZrcamn\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCZrcamn\App_KernelDevDebugContainer([
    'container.build_hash' => 'CZrcamn',
    'container.build_id' => '4d04a70b',
    'container.build_time' => 1766506874,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCZrcamn');
