<?php

namespace ContainerCZrcamn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMessenger_Transport_AsyncService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'messenger.transport.async' shared service.
     *
     * @return \Symfony\Component\Messenger\Transport\TransportInterface
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Transport/Receiver/ReceiverInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Transport/Sender/SenderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Transport/TransportInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Transport/TransportFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Transport/TransportFactory.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Transport/Serialization/SerializerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Transport/Serialization/SigningSerializer.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Transport/Serialization/PhpSerializer.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/string/LazyString.php';

        return $container->privates['messenger.transport.async'] = (new \Symfony\Component\Messenger\Transport\TransportFactory(new RewindableGenerator(function () use ($container) {
            yield 0 => (new \Symfony\Component\Messenger\Bridge\Redis\Transport\RedisTransportFactory());
            yield 1 => ($container->privates['messenger.transport.sync.factory'] ?? $container->load('getMessenger_Transport_Sync_FactoryService'));
            yield 2 => ($container->privates['messenger.transport.in_memory.factory'] ?? $container->load('getMessenger_Transport_InMemory_FactoryService'));
            yield 3 => $container->load('getMessenger_Transport_Doctrine_FactoryService');
        }, 4)))->createTransport('redis://redis:6379/messages', ['transport_name' => 'async'], new \Symfony\Component\Messenger\Transport\Serialization\SigningSerializer(new \Symfony\Component\Messenger\Transport\Serialization\PhpSerializer(), \Symfony\Component\String\LazyString::fromCallable(#[\Closure(name: '.messenger.signing_serializer.signing_key', class: 'string')] fn () => ($container->privates['.messenger.signing_serializer.signing_key'] ?? $container->load('get_Messenger_SigningSerializer_SigningKeyService'))), []));
    }
}
